[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc-version = "0.8.15"
optimizer = true
via_ir = true
optimizer_runs = 1000000
bytecode_hash = "none"

[profile.ci]
fuzz = { runs = 500 }
invariant = { runs = 50 }

[profile.ci_invariant]
invariant = { runs = 50, depth = 500 }

[invariant]
call_override = false
runs = 25
depth = 100
dictionary_weight = 80
fail_on_revert = false
include_push_bytes = true
include_storage = true
optimizer = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
