name: test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge unit tests
        run: |
          forge test -vvv --no-match-contract "FranchiserFactoryInvariantTest|IntegrationTest"
        id: unit-test

      - name: Run Forge invariant tests
        run: |
          forge test -vvv --match-contract FranchiserFactoryInvariantTest
        id: invariant-test

      - name: Run Forge integration tests
        env:
          FORK_URL: ${{ secrets.FORK_URL }}
        run: |
          forge test -vvv --match-contract IntegrationTest --fork-url $FORK_URL
        id: integration-test
